Importing Libraries

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from keras.models import Sequential, Model

In [ ]:
model_cnn = Sequential([
    Conv2D(64, 3, input_shape=(128,128,1), use_bias=True ),
    MaxPooling2D(pool_size=4),
    Flatten(),
    Dropout(0.5),
    Dense(1, activation='softmax')
])

In [ ]:
model_cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 64)      640       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 64)        0         
 D)                                                              
                                                                 
 flatten (Flatten)           (None, 61504)             0         
                                                                 
 dropout (Dropout)           (None, 61504)             0         
                                                                 
 dense (Dense)               (None, 1)                 61505     
                                                                 
Total params: 62145 (242.75 KB)
Trainable params: 62145 (242.75 KB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [ ]:
model_cnn.save('simple_cnn.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
input_shape = (4, 28, 28, 3)

In [ ]:
x = tf.random.normal(input_shape)

In [ ]:
x.shape

In [ ]:
input_shape[1:]

In [ ]:
y = Conv2D(2, 2, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 4, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, [3,2], activation='relu', input_shape=input_shape[1:])(x)


In [ ]:
y.shape

TensorShape([4, 27, 27, 2])

In [ ]:
y[0].shape

TensorShape([27, 27, 2])

In [ ]:
z = MaxPooling2D(pool_size=3, strides=3)(y)

In [ ]:
z.shape

TensorShape([4, 9, 9, 2])

In [ ]:
z[0].shape

TensorShape([9, 9, 2])

In [ ]:
ab = Flatten()(z)

In [ ]:
ab.shape

TensorShape([4, 162])

In [ ]:
ab[0].shape

TensorShape([162])

In [ ]:
abz = Dropout(0.5,  noise_shape=None, seed=10)(ab)

In [ ]:
abz.shape

TensorShape([4, 162])

In [ ]:
abz[0]

<tf.Tensor: shape=(162,), dtype=float32, numpy=
array([1.7006719 , 0.84721583, 1.4905524 , 1.2639577 , 2.1336374 ,
       0.9311424 , 0.92965597, 1.9250734 , 1.3203968 , 1.2322798 ,
       2.5249102 , 1.5164788 , 1.7885084 , 0.7019322 , 1.2632561 ,
       0.71780294, 2.928642  , 0.7372911 , 1.9785268 , 1.4802388 ,
       1.2953123 , 2.5389562 , 1.7077615 , 1.4170403 , 2.5000226 ,
       1.0770724 , 2.5256977 , 1.9792552 , 2.1763256 , 2.2909076 ,
       2.5295444 , 1.0544974 , 0.95244765, 0.8966906 , 3.5065143 ,
       0.95624363, 1.3315282 , 0.        , 3.3739839 , 2.2019677 ,
       1.3048316 , 2.3023481 , 3.764534  , 2.3004003 , 2.416278  ,
       1.5015817 , 0.33956072, 1.2667838 , 1.571293  , 1.7089264 ,
       0.32248658, 0.96154594, 1.5920677 , 1.3509374 , 1.9912541 ,
       1.2537525 , 0.8358885 , 2.5646238 , 1.7988632 , 0.97174335,
       1.0020282 , 2.1354074 , 0.83639467, 1.8095841 , 0.9387448 ,
       1.9674745 , 1.0973308 , 0.9979218 , 2.5925608 , 3.7407548 ,
       2.52744

In [ ]:
final = Dense(10, activation='softmax')(abz)

In [ ]:
final

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.00872255, 0.05976781, 0.22009014, 0.10930702, 0.01670565,
        0.02613832, 0.0176127 , 0.02363251, 0.34028998, 0.17773327],
       [0.00147255, 0.06653058, 0.20937705, 0.10282306, 0.02483511,
        0.1268296 , 0.00056987, 0.01467465, 0.36729535, 0.0855922 ],
       [0.00147559, 0.04076376, 0.09908215, 0.22410156, 0.04119741,
        0.01220924, 0.0009862 , 0.02408347, 0.19128641, 0.36481413],
       [0.00593992, 0.03761481, 0.2876138 , 0.21331993, 0.03805625,
        0.06011985, 0.00098581, 0.03926578, 0.2051749 , 0.11190898]],
      dtype=float32)>

In [ ]:
final_relu = Dense(10, activation='relu')(abz)

In [ ]:
final_relu

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.        , 0.        , 0.        , 0.        , 2.7466533 ,
        2.6692245 , 1.4230039 , 0.        , 0.        , 0.        ],
       [0.        , 0.35345748, 0.        , 0.        , 0.8550787 ,
        2.6555407 , 2.8982127 , 0.        , 2.8687637 , 0.        ],
       [0.        , 1.2161232 , 0.        , 1.0430071 , 1.5173734 ,
        2.288494  , 2.1045606 , 0.        , 1.4757283 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.69015   ,
        3.023362  , 2.11029   , 0.16210069, 1.2733552 , 0.        ]],
      dtype=float32)>